spring.application.name=CHAT-BOT
server.port=8008

# Optional: Increase timeout for LLM responses
spring.mvc.async.request-timeout=120000


# Development mode
spring.devtools.restart.enabled=true


# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

## H2 Database
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dcbapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view=false
#
spring.thymeleaf.check-template-location=false
